import 'package:flutter/material.dart';

class PageConst {
  static const String authG = "/authG";

  static const String login = "/login";
  static const String signup = "/register";
  static const String chatPage = "/chatPage";
  static const String addContactScreen = "/addContactScreen";
  static const String autoGeneratedChatPage = "/autoGeneratedChatPage";
  static const String homePage = "/homePage";
  static const String homePageContacts = "/homePageContacts";
  static const String homePageRequests = "/homePageRequests";
  static const String pastChatListPage = "/pastChatListPage";
  static const String pastChatView = "/pastChatView";
  static const String contactsView = "/ContactsPage";
  static const String chatView = "/chatPage";
  static const String userProfilePage = "/userProfilePage";
  static const String userPrivateProfilePage = "/userPrivateProfilePage";
  static const String imageView = "/imageView";

}
